### ISSUE TITLE
Unable to find widget during build

### ISSUE THREAD

**Issue by raghavb11** [bsgriggs/mendix-dropdown-date-picker#1]
We are using this widget in one of our projects but mendix is unable to detect the widget from the widgets folder and throws an error unable to find widget default.DropDownDatePicker. Please help.

**Comment by bsgriggs** [comment]
Hello, what Mendix version are you using?

**Comment by raghavb11** [comment]
We are on 9.6.6

**Comment by raghavb11** [comment]
This is the error message - Dropdown Date Picker 'dropdownDatePicker1': Could not find widget 'Dropdown Date Picker' in the 'widgets' directory. It works when we run locally but this error comes up when trying to deploy on our private cloud.

**Comment by bsgriggs** [comment]
If you make a copy of the deployment package and rename the file extension from .mda to .zip, then you should be able to open up the deployment package and view its contents.

Inside the deployment package, do you see a directory \web\widgets\dropdowndatepicker?

**Comment by raghavb11** [comment]
Thanks for pointing that out. For some reason, the widget was not getting committed to the deployment package. When I manually uploaded it there it build successfully.
