### ISSUE TITLE
Locale selection

### ISSUE THREAD

**Issue by RuudFl** [bsgriggs/mendix-dropdown-date-picker#3]
Being able to select a locale would be a great feature for this widget. Great widget nonetheless!

**Comment by bsgriggs** [comment]
Hi there,

Can you elaborate more on your use case? This widget is for selecting date values and should almost always be used with non-localized dates (i.e. birthdays).

**Comment by RuudFl** [comment]
Hi Benjamin,

The month names are now hard-coded in English. It would be great to set a locale / language in the widget (f.i. nl) so that month names would be retrieved for that locale and would appear in the Dutch language in the month dropdown. Or even better, use the locale set in the mendix project (don't know if this is possible).

Regards

**Comment by bsgriggs** [comment]
Hi there,

I've just released version 2.0.0 in the [marketplace](https://marketplace.mendix.com/link/component/119971) which should automatically localize the names of the months based on the current user's language settings. Please give it a test and let me know if you have any issues.
